compile_to: 
	javac -d $(DIR) $(FILE_NAME)
# make FILE_NAME="RefDataStructures.java" compile_to DIR="bin"
run_class_at:
	java -cp $(CLASS_PATH) $(CLASS_NAME)
# make CLASS_NAME="RefDataStructures" run_class_at CLASS_PATH="bin"